### ISSUE TITLE
All tokens with exp in payload permanently expired

### ISSUE THREAD

**Issue by raghavendranvenkateswaran** [auth0/node-jsonwebtoken#209]
Tokens generated with "exp" in the payload are permanently expired since creation.
 e.g: 
var token = jwt.sign(req.body,cert); for signing with below input
{
    "sub": "admin@admin.com",
    "iss": "https://apevolve.tcs.com",
    "permissions": "Admin",
    "exp":60
}

are always returning 
{
  "name": "TokenExpiredError",
  "message": "jwt expired",
  "expiredAt": "1970-01-01T00:01:00.000Z"
}
on trying the verify token call 
var decoded = jwt.verify(token,cert);

both calls are made from the same machine.

**Comment by trendsetter37** [comment]
@raghavendranvenkateswaran 

Try

```
{
  "sub": "admin@admin.com",
  "iss": "https://apevolve.tcs.com",
  "permissions": "Admin",
  "exp": (Date.now() / 1000) + 60
}
```

Note that javascripts `Date` class operates with milliseconds so you need to convert to seconds; then add the 60 seconds you were using before. This will produce the current date in seconds since Jan 1970 plus your additional 60 seconds which will give you your future expiration date.

This tripped me up today because the usage explanation in the README makes it seem like you only need the "time span", however I could only get the expected behavior by doing the above. Which is basically calculating what the expiration would be in total seconds from the unix epoch time.

Should that part be done in the backend? Or should the docs change?

**Comment by raghavendranvenkateswaran** [comment]
I think that should be done in the backend.If needed a present Date can be added to options..
@trendsetter37 as for the solution you provided... I am presently calling the JWT token node js service from a Java Client and would wish for the client to set the expiry on time span (so that dont face system time discrepancies and format issues). 
Also , if I am trying with the example you provided above.. The "exp" field only takes in numbers and refuses to take this expression..? Any help on how I do it from my Java call to nodejs service calling jwt.sign...

**Comment by raghavendranvenkateswaran** [comment]
I tried making some changes to let it reflect timestamp in expiry check calculations...

if we change line 147 in index.js from if (Math.floor(Date.now() / 1000) >= payload.exp + (options.clockTolerance || 0)) 
to
if (Math.floor(Date.now() / 1000) >= payload.exp + (options.clockTolerance || 0) + payload.iat)
then it works fine...
Also if anyone wants to give their own timestamp... they can use "iat" to provide value..
@trendsetter37 what do you think?

**Comment by omsmith** [comment]
The _exp_ field is defined, by spec, as the timestamp so the change you're asking for isn't possible.

This library provides `options.expiresIn` to provide "relative to now", which is what you're looking for.

**Comment by raghavendranvenkateswaran** [comment]
@omsmith my bad. I will give it a try with options.expiresIn for my requirement.Thanks

**Comment by nimatullah** [comment]
Hi @raghavendranvenkateswaran , I have the same problem. Can you guide me how to solve this problem, since I am using `express-jwt`.

Thanks
