### ISSUE TITLE
expiresIn Does not set expiration correctly

### ISSUE THREAD

**Issue by eddievagabond** [auth0/node-jsonwebtoken#234]
I am having a really difficult time getting node-jsonwebtoken to set expiration correctly. It seems to set time from epoch start instead of from Now. Perhaps I am doing something incorrectly. Below is my code. Any clarification would be greatly appreciated.

```
let payload = {
        iss: config.jwt.issuer,
        aud: config.jwt.audience,
        userId: req.user.id,
        username: req.user.username,
        firstName: req.user.firstName,
        lastName: req.user.lastName,
        roles: req.user.roles,
        expires: expiry.getTime()
};

let options = {
        algorithms: ['HS256'],
        expiresIn: '2 days'
};

let token = jwt.sign(payload, config.jwt.secret, options);
console.log(moment(jwtDecode(token).exp).format('MMMM Do YYYY, h:mm:ss a'));

```

results in: January 17th 1970, 6:27:08 pm

Am I just not understanding the documentation? Any help would be greatly appreciated.

**Comment by eddievagabond** [comment]
I stupidly forgot to add iat: Date.now() to payload .
I can set expiration in milliseconds, but something like expiresIn: '2h' does not work still.

**Comment by jfromaniello** [comment]
That's weird... the default for iat is `Date.now()`:

https://github.com/auth0/node-jsonwebtoken/blob/master/sign.js#L97
https://github.com/auth0/node-jsonwebtoken/blob/master/sign.js#L113

**Comment by eddievagabond** [comment]
I am using it in conjunction with node-oauth2-server to generate my tokens for a password and refresh grant. It is implemented in the generateToken (type, req, callback) function. I don't know how that could affect it, but I have never had this problem until now. Thanks for taking a look. If I have some spare time I will try to debug it to find out exactly why this is occurring

**Comment by mgoria** [comment]
Hi @eddievagabond, have you figured out how to solve this issue?
For me it also sets time smth like `Sun Jan 18 1970 ...`

**Comment by john-mcgowan1992** [comment]
I briefly just ran into this issue. Per the Docs, ```iat``` and ```expiresIn``` are represented using Numeric Date: ```A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds.``` whereas Javascript Date objects use milliseconds elapsed since 1970-01-01T00:00:00Z ([mdn).](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) @mgonto I'm sure you probably resolved this by now, but if you we're trying to convert your JWT expiration/issued at values to JS Dates, first try multiplying you ```iat``` or ```exp``` value by 1000.

**Comment by adekoyejoakinhanmi** [comment]
@john-mcgowan1992 Does this mean that I have to explicitly state iat and exp, if I want current date in the token?

**Comment by john-mcgowan1992** [comment]
@adekoyejoakinhanmi per the docs, ```iat``` will be set in the token by default to the current time represented as seconds elapsed since Jan 1 1970, unless otherwise specified (for example, if you want to back date the token). As for ```exp``` there is no default value so it's up to you to decide how long your want your token to stay valid.

```Generated jwts will include an iat (issued at) claim by default unless noTimestamp is specified. If iat is inserted in the payload, it will be used instead of the real timestamp for calculating other things like exp given a timespan in options.expiresIn.``` - [docs](https://www.npmjs.com/package/jsonwebtoken#jwtsignpayload-secretorprivatekey-options-callback)
