### ISSUE TITLE
 How to generate Personal Access Token in JWT?

### ISSUE THREAD

**Issue by ovaiskhan11** [auth0/node-jsonwebtoken#289]
I am using JWT in my sails.js project and I want to generate Personal Access Token like in Laravel Passport Authentication. And user can also re-generate their Personal Access Token.

Waiting for positive response.

**Comment by ziluvatar** [comment]
Can you elaborate the question? Is it about to add support in the library for some aspect of it? Is it a design question by using this library?

**Comment by ziluvatar** [comment]
@ovaiskhan11 I'm going to close this issue, if you are still interested in this topic you can reopen it.

**Comment by gonzalad** [comment]
I add this link https://community.auth0.com/questions/9121/server-api-authorization-tokens-for-non-interactiv which illustrates this feature

**Comment by ziluvatar** [comment]
I think I miss some part about this. Basically it is about having a JWT that does not expire with some claims, and the user could revoke it, so at that point the token is not longer valid.

1. Some system needs to create that token with the claims on it. It can be JWT or a random id with a record in db.
2. Some system will verify the validity (checking in db or verifying JWT signature)
  * Here there is a point for JWT format: Since the user can revoke the token, this system needs to validate in some place that this JWT has not been revoked (using `jti` claim?).

Thus, I don't get what stops anyone from using the library as is. If some can bring the problems, we can chat about it.
