### ISSUE TITLE
jwt sign with private key

### ISSUE THREAD

**Issue by paulddrix** [auth0/node-jsonwebtoken#296]
Helo, I was wondering why jwt signs a token with a private key and not a public one the way other libraries to encrypt do, like openpgpjs. Thank you for your time.

**Comment by goloroden** [comment]
Because this is how digital signatures work ;-)

If you encrypt something using the public key, then only the person who knows the private key can decrypt it. This is useful is you want to send a secret message to a person X, and only X shall be able to read it.

Anyway, X can not know whether the message was really created by you. For this you need to add a digital signature. You do this by encrypting using your private key. Then it can only be decrypted using your public key. Of course, since it is public, everyone can do it - but it could have been signed by you.

Since the `sign` function is about signing, not encrypting, you use the private key, not the public one.

Hope this helps.
