### ISSUE TITLE
Can't resolve 'dns' in ./~/isemail/lib/isemail.js

### ISSUE THREAD

**Issue by vivian7169** [auth0/node-jsonwebtoken#317]
When I imported 'jsonwebtoken' into angular2 web app, encountered error as below:

// example
import * as jwt from 'jsonwebtoken';
let token = jwt.sign({
                    username: username,
                    role: role,
                    exp:  Math.floor(Date.now() / 1000) + (60 * 20)
                }, 'xxx');

// error
ERROR in ./~/isemail/lib/isemail.js
Module not found: Error: Can't resolve 'dns' in '/Users/aaa.../myApp/node_modules/isemail/lib'
 @ ./~/isemail/lib/isemail.js 45:10-24
 @ ./~/isemail/index.js
 @ ./~/joi/lib/string.js
 @ ./~/joi/lib/index.js
 @ ./~/jsonwebtoken/sign.js
 @ ./~/jsonwebtoken/index.js
 @ ./src/app/authentication/fake/fake-backend.ts
 @ ./src/app/authentication/fake/index.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

**Comment by ziluvatar** [comment]
We use `joi` for the validations, there are some issues using it in the browser instead of in NodeJS.
The issue you describe is in their repo too https://github.com/hapijs/joi/issues/706

Just for curiosity, may I ask what is the secret you want to use to sign in a browser? the user password? And what is the purpose of signing in browser for you?

**Comment by yvele** [comment]
@ziluvatar I have the same issue..

I'm using it server side but I also need it browser side to implement a mock for development purpose..

**Comment by ziluvatar** [comment]
Hi @yvele, as commented [here](https://github.com/auth0/node-jsonwebtoken/issues/195#issuecomment-215689756), for signing in browser you can take a look to  https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-generation

I will close this issue, be free to re-open it if you have outstanding problems/questions.

**Comment by yvele** [comment]
@ziluvatar Oh thank you so much for the tutorial.. nice one 👍

**Comment by jdrew1303** [comment]
I also ran into the same problem and went for a little bit of a different solution:

If youre using webpack or browserify you can shim out modules to make them point to other modules. In this case we replace calls to `require('joi')` using the module loader.

For a bit more details see the following repos (depending on which version of joi you're using):
- https://github.com/jeffbski/joi-browser
- https://github.com/jeffbski/joi-full

This will take care of allowing you to load in the browser or in node (handy for isomorphic applications).

__NOTE:__ it may be worth bundling this for browser use and adding an entry in your package.json to toggle depending on the build. Id be willing to add a pull request for this if you're interested. On the surface it would seem like a better choice to use another library to handle decode and verification but this one is in active development and will probably outlast any of the framework specific libraries. Not to mention that it makes life easier for developers that do full stack development (like yours truly :grin:). 

Taken from their docs: 

### Isomorphic / Universal JS - using in browser and on server (Node.js)

If you want to use `joi` with Node.js and `joi-browser` for browser use then you can follow one of these recipies.

#### Browserify

```bash
npm install joi-browser
npm install joi
```

Add the following to your app's package.json which will tell browserify to use joi-browser instead of joi when bundling for the browser.

```json
  "browser": {
    "joi": "joi-browser"
  },
```

So in your code, you just require `joi` and browserify will automatically switch it with joi-browser when it bundles.

```javascript
var Joi = require('joi');
```

See `examples/browserify-basic`

#### Webpack

```bash
npm install joi-browser
npm install joi
```

Add the following to your app's webpack.config.js to alias joi to joi-browser

```javascript
  resolve: {
    alias: {
      joi: 'joi-browser'
  }
```

Note: if you are using webpack with a babel loader you may need to exclude `joi-browser` (or node_modules) from being run through babel again.

In your webpack.config.js loaders, add an `exclude: [ /joi-browser/ ]`.



So in your code, you just require `joi` and webpack will automatically switch it with joi-browser when it bundles.

```javascript
var Joi = require('joi');
```

See `examples/webpack-basic`

**Comment by jhalbsgut** [comment]
@jdrew1303 Thanks for the doc refs. The webpack one was just what I needed!

**Comment by megamindbrian** [comment]
Why does jsonwebtoken need isemail?  Why does isemail need dns?

**Comment by jdrew1303** [comment]
@jhalbsgut No problem, glad to help. I ran into the same issues so its a pain. 

@megamindbrian 

They're using `joi` for validations, and `joi` is pulling these in unfortunately. 👎 Joi is a great lib for validations but it freaks out in the browser.

Here's the offending bit: https://github.com/auth0/node-jsonwebtoken/blob/2ec4960b8b944682aa486a4f2d054d731baf8158/sign.js#L7

**Comment by megamindbrian** [comment]
It all looks like boilerplate to me ;)

**Comment by Chaoste** [comment]
I'm having the same issues - no webpack right now available.

I just want to use opentok, which uses jsonwebtoken. Can you please update your dependencies? It's just switching to joi 10.6.0 (their fix was added a month ago)
