### ISSUE TITLE
Confused version management

### ISSUE THREAD

**Issue by bigZ-again** [auth0/node-jsonwebtoken#340]
When i run npm install, I download the PR release at 29 Nov 2016, not the latest release at 8 Mar 2017.
But I read README.md on github.com, It's latest release that include new feature(Make Options object optional for callback-ish sign) that not in PR release.

**Comment by ziluvatar** [comment]
Hi @bigZ-again, not sure I understand. In any case, the pull request about "make options object optional for callback-ish sign" was merged but I didn't create a new version because I wanted to include other changes, unfortunately, I didn't add them yet, so that the README (master) vs Last Release could create confusion.

I just released a new version with that change: v7.4.0. Sorry for the confusion.

**Comment by bigZ-again** [comment]
thanks
