### ISSUE TITLE
Question: use case blind signatures

### ISSUE THREAD

**Issue by rriemann** [auth0/node-jsonwebtoken#387]
Hello,

I'm new to JWT and would like to know if the standard and implementation allows for blind signatures, e.g. based on RSA.

I googled the entire web and blind signatures with JS is either super trivial or super complicated. I haven't found any implementation yet I could learn from.

**Comment by sjudson** [comment]
No, the JOSE/JWA/JWS specifications don't include any provisions for blind signatures, or really privacy-protecting technologies in general. So unfortunately there is no way to provide them within the bounds of the specification, and it's not something we have interest in ourselves. Finally, because of the various complexities (meant informally) which must be surmounted to get the proper privacy behavior out of them, it's not something that that can just be independently rolled, so we wouldn't be interested in adding support even if someone came along with a PR, since it's just be useless and misleading for any general federation purposes.
