### ISSUE TITLE
how to set expiresIn never expire ?

### ISSUE THREAD

**Issue by numa001** [auth0/node-jsonwebtoken#417]

**Comment by odarbelaeze** [comment]
just don't put it at all 🤔

**Comment by ziluvatar** [comment]
@odarbelaeze is right. If you don't pass `expireIn` option or `exp` claim there will not be any `exp` claim, so the JWT does not have any expiration.

**Comment by markuso** [comment]
Does this no longer work in the latest version? We used to be able to enter 0  (zero) as the `expireIn` to never expire the token. Now it forces us to enter a specific length of time. Is that intentional?

**Comment by ziluvatar** [comment]
@markuso I tested with v7.4.3 and the use case you mention does not work either, it will add an expiration with the same second as the `iat`, so the token would be useless since it's expired at the same moment it was created.

With both v8 and v7:
```
> jwt.decode(jwt.sign({a:1},'ssh'))
{ a: 1, iat: 1516971150 }
> jwt.decode(jwt.sign({a:1},'ssh', { expiresIn: 0 }))
{ a: 1, iat: 1516971152, exp: 1516971152 }
```

**Comment by danikane** [comment]
As @odarbelaeze says - don't pass expiresIn to the jwt options and you'll have a token with no expiration.

**Comment by markuso** [comment]
I was passing an `undefined` value into the `expiresIn` property and it was failing. So I assumed it was forcing us to enter a value like `0` or greater. I now make sure that I don't declare the property at all instead of allowing an `undefined` value to be set. I feel that it should take care of the `undefined` value internally, in my opinion, to behave like it was unset. Cheers!

**Comment by gmaijoe** [comment]
bump

**Comment by excitepv** [comment]
On the other hand, we can use the below option while verifying the token
**ignoreExpiration: if true do not validate the expiration of the token.**

**Comment by ricardotfs** [comment]
it's very simple code below:
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options => 
                {
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateIssuer = true,
                        ValidateAudience = true,
                        ValidateLifetime = false,
                        ValidateIssuerSigningKey = true,
                        ValidIssuer = "gvp.ideacrm.com.br",
                        ValidAudience = "gvp.ideacrm.com.br",
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration["SecurityKey"]))
                    };

                    options.Events = new JwtBearerEvents
                    {
                        OnAuthenticationFailed = context =>
                        {
                            Console.WriteLine($"Token inválido.....{context.Exception.Message}");
                            return Task.CompletedTask;
                        },
                        OnTokenValidated = context =>
                        {
                            Console.WriteLine($"Token válido.....{context.SecurityToken}");
                            return Task.CompletedTask;
                        }
                    };
                });

**Comment by PedroRuiz** [comment]
Never... is too much time. But, I think that 9999 years is a reasonable meaning of 'never':
`
const token = jwt().sign({
    uuid:data,
    apikey
  },
  '9999 years'
  )
`
produces my verified token: 
`
{
  uuid: 'fcaf0b39-0cf6-4814-ba54-634f5061b352',
  apikey: 'TAAR8M9-32CMACE-K0V48EV-3Z7ASJB',
  iat: 1581155672,
  exp: 317125598072
}
`
Since: 2020-02-08T10:54:32+01:00
Expire: 12019-04-24T05:54:32+02:00

Perhaps in 9999 years your application runs in replicating beings in other galaxy, even other circumstances that we can't even think about now

**Comment by Root-Control** [comment]
> Never... is too much time. But, I think that 9999 years is a reasonable meaning of 'never':
> `const token = jwt().sign({ uuid:data, apikey }, '9999 years' )`
> produces my verified token:
> `{ uuid: 'fcaf0b39-0cf6-4814-ba54-634f5061b352', apikey: 'TAAR8M9-32CMACE-K0V48EV-3Z7ASJB', iat: 1581155672, exp: 317125598072 }`
> Since: 2020-02-08T10:54:32+01:00
> Expire: 12019-04-24T05:54:32+02:00
> 
> Perhaps in 9999 years your application runs in replicating beings in other galaxy, even other circumstances that we can't even think about now

I'm from the future, man, your token just expired, and we can't use the API, the world is in chaos

**Comment by trandaison** [comment]
> Never... is too much time. But, I think that 9999 years is a reasonable meaning of 'never':
const token = jwt().sign({ uuid:data, apikey }, '9999 years' )
produces my verified token:
{ uuid: 'fcaf0b39-0cf6-4814-ba54-634f5061b352', apikey: 'TAAR8M9-32CMACE-K0V48EV-3Z7ASJB', iat: 1581155672, exp: 317125598072 }
Since: 2020-02-08T10:54:32+01:00
Expire: 12019-04-24T05:54:32+02:00
> 
> Perhaps in 9999 years your application runs in replicating beings in other galaxy, even other circumstances that we can't even think about now

⟟'⋔ ⎎⍀⍜⋔ ⏁⊑⟒ ⎎⎍⏁⎍⍀⟒, ⋔⏃⋏, ⊬⍜⎍⍀ ⏁⍜☍⟒⋏ ⟊⎍⌇⏁ ⟒⌖⌿⟟⍀⟒⎅, ⏃⋏⎅ ⍙⟒ ☊⏃⋏'⏁ ⎍⌇⟒ ⏁⊑⟒ ⏃⌿⟟, ⏁⊑⟒ ⍙⍜⍀⌰⎅ ⟟⌇ ⟟⋏ ☊⊑⏃⍜⌇

**Comment by mdfahaduddin** [comment]
> Never... is too much time. But, I think that 9999 years is a reasonable meaning of 'never': `const token = jwt().sign({ uuid:data, apikey }, '9999 years' )` produces my verified token: `{ uuid: 'fcaf0b39-0cf6-4814-ba54-634f5061b352', apikey: 'TAAR8M9-32CMACE-K0V48EV-3Z7ASJB', iat: 1581155672, exp: 317125598072 }` Since: 2020-02-08T10:54:32+01:00 Expire: 12019-04-24T05:54:32+02:00
> 
> Perhaps in 9999 years your application runs in replicating beings in other galaxy, even other circumstances that we can't even think about now
🤣🤣🤣🤣🤣🤣🤣🤣
