### ISSUE TITLE
TypeError: crypto.createHmac is not a function

### ISSUE THREAD

**Issue by AkhilNaidu09** [auth0/node-jsonwebtoken#419]
I am facing a issue while converting object to jwt token here is the following code and error blocks can anyone give me solution for this

  ```
const secret = "werxhqb98rpaxn39848xrunpaw3489ruxnpa98w4rxn";
        function TokenGenerator(secretOrPrivateKey, secretOrPublicKey, options) {
            this.secretOrPrivateKey = secretOrPrivateKey;
            this.secretOrPublicKey = secretOrPublicKey;
            this.options = options; //algorithm + keyid + noTimestamp + expiresIn + notBefore
        }

        TokenGenerator.prototype.sign = function (payload, signOptions) {
            const jwtSignOptions = Object.assign({}, signOptions, this.options);
            return jwt.sign(payload, this.secretOrPrivateKey, jwtSignOptions);
        }

        const tokenGenerator = new TokenGenerator(secret, secret, { algorithm: 'HS256', keyid: '1', noTimestamp: false, expiresIn: '2m', notBefore: '2s' })
        var token = tokenGenerator.sign(user, { audience: 'myaud', issuer: 'myissuer', jwtid: '1', subject: 'user' })
        console.log(token);
    }
```

error:
```

LoginComponent.html:16 ERROR TypeError: crypto.createHmac is not a function
    at Object.sign (index.js:34)
    at Object.jwsSign [as sign] (sign-stream.js:23)
    at Object.webpackJsonp.../../../../jsonwebtoken/sign.js.module.exports [as sign] (sign.js:186)
    at TokenGenerator.sign (login.component.ts:45)
    at LoginComponent.webpackJsonp.../../../../../src/app/login/login.component.ts.LoginComponent.onLoggedin (login.component.ts:50)
    at Object.eval [as handleEvent] (LoginComponent.html:16)
    at handleEvent (core.es5.js:11852)
    at callWithDebugContext (core.es5.js:13060)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12648)
    at dispatchEvent (core.es5.js:8830)
```

Using Angular 4

**Comment by rbedemann** [comment]
we're facing the same issue, although our IDE (IntelliJ IDEA) knows about the function.

**Comment by ziluvatar** [comment]
Let's see if someone from the community has a solution. Since the library expects to work under NodeJS environment I'm not sure if that browser/builder has some issue/lack for crypto library.

If I may ask, why do you need to create a JWT token and use HMAC from browser code? It is usually the other way around, server will sign and browser/server will verify.

**Comment by rbedemann** [comment]
In our case we're using the sign method for testing purposes. Because it is more comfortable to write tests with something like:
`
let payloadWithExp = {
    "exp": 1508932433
  };
   const accessToken =  sign(payloadWithExp,"test-secret")
`

instead of
`const accessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjcyMjc4NDY5MTJ9.g6aWa5kckTBIwrxOg5I-z7xUmSagrPI7CGZWksFE4Fg";`

because we can easily change the values to what we need...

**Comment by ziluvatar** [comment]
I see, I'd say you could use this other library https://github.com/kjur/jsrsasign/wiki/Tutorial-for-JWT-generation. We've recommended it in the past for browsers.
