### ISSUE TITLE
Build pipeline

### ISSUE THREAD

**Issue by JacoKoster** [auth0/node-jsonwebtoken#486]
I have already 
- added a basic .editorconfig in #480 
- made a PR to upgrade to the latest Node-versions in #470 
- made a PR for adding code-coverage with Istanbul in #468 

I'd like to add two more things to make working on this repository a little bit easier
- change the jshint-config to a eslint-config
- change travis configuration to the following buildsteps (and change the package.json accordingly)
1. test
2. coverage
3. nsp
4. lint

Would this be a good idea to do?

**Comment by ziluvatar** [comment]
> change the jshint-config to a eslint-config

Ok with that. Do you mean to keep both or to remove the jshint?

> change travis configuration to the following buildsteps...

Ok. Do you mean to modify the current `test` script in package.json and remove from there test + coverage + nsp + cost-of-modules and create build steps for them in travis?

About the order, probably it is better to set the lint as first step because it is faster to get a failure and avoid waiting for tests to pass to then get an error from the linter.

**Comment by JacoKoster** [comment]
I fully endorse #490 as a way to solve this, i will add another PR to make sure the build breaks when doing tests.

That would change the order (indeed) to lint - test (with blocking coverage-check) - nsp

**Comment by JacoKoster** [comment]
I am considering this one finished, thanks @MitMaro and @ziluvatar :-)
