### ISSUE TITLE
When the time interval is very short，it will generate the same token in the certain condiction ?

### ISSUE THREAD

**Issue by garysdevil** [auth0/node-jsonwebtoken#570]
Could you tell me  how does it generate different token when using the same head, payload, secret but different time ？
When the time interval is less than 200ms，it may occure below.
![image](https://user-images.githubusercontent.com/41293784/51652603-320c4d80-1fcb-11e9-83dc-cf192bdeaabc.png)
Could you tell me  how long the least time interval it will not occur the same token??

**Comment by ziluvatar** [comment]
By default, every second. The reason is that only the `iat` ("issued at" claim) would be different, it holds the time in seconds when the token was issued.

If you need to have unique tokens you could use the `jwtid` option with a unique identifier for each token that will set the `jti` claim in the token.

**Comment by panva** [comment]
@garysdevil HS and RS signatures do not include any randomly generated padding, hence their signature is the same given the same payload.

To get a random signature regardless of the payload you should be using ES or [PS](https://github.com/auth0/node-jsonwebtoken/pull/573) signatures.
