### ISSUE TITLE
Cannot read property 'isZero' of undefined

### ISSUE THREAD

**Issue by amirklick** [auth0/node-jsonwebtoken#572]
Having trouble generating a token when running code below:
`const token = jwt.sign(tokenPayload, tokenSecret, { algorithm: 'RS256' });`
(where tokenSecret is a public key, same one used by server)

If I don't include the `algorithm` option it works, but then the server is unable to `verify` saying `invalid algorithm`. Which makes sense because algorithm on server is `RS256` and from my understanding, `jwt.sign` uses `HS256` by default.

But when I do include the `algorithm` option, `jwt.sign` throws an error saying `Cannot read property 'isZero' of undefined` caused by the `bn` package which I assume is a dependancy of dependancies of `jsonwebtoken`.

Any ideas?

**Comment by ziluvatar** [comment]
> where tokenSecret is a public key, same one used by server

If you are using asymmetric algorithms (like RSxxx), for JWT signing you need to use the private key, so that the resulted token can be verified by any third party using the public key.

About the `isZero` error, no idea, I checked the code of the library (including `node_modules`), I couldn't find it anywhere in the production code (maybe it is NodeJS code).

I tried to use a public key as `tokenSecret` and I got `Error: error:0906D06C:PEM routines:PEM_read_bio:no start line`. Did you find out?

**Comment by amirklick** [comment]
I suspected I needed a private key but haven't found it in Cognito.
Any idea where I could get the private key from?

Haven't found the cause or a solution to the `isZero` error, but I'm guessing it errors because I'm using a public key since Cognito uses `RS256` algorithm.

**Comment by ziluvatar** [comment]
> Any idea where I could get the private key from?

No idea. I'm going to close it, if you found the issue or the private key and you have time give us a summary that'd be interesting :)

**Comment by barouchk** [comment]
@amirklick I had the same issue.

check that you putting the private key of the certificate.
It will be inside the .pem file
