### ISSUE TITLE
Support verifying private claims

### ISSUE THREAD

**Issue by dolegi** [auth0/node-jsonwebtoken#583]
I can't see it documented anywhere and I can't find it in the code.
Example
token payload
```javascript
{
  "privateClaim": "private",
  "iss": "...",
  "sub": "...",
  "aud": "...",
  "iat": 1551692259,
  "exp": 1551693159
}
```
```javascript
var cert = fs.readFileSync('public.pem');  // get public key
jwt.verify(token, cert, { privateClaim: "private" }, function(err, decoded) {
  // no err
})
```

Is this a feature that would be considered? Currently I have to verify the token and then verify against private claims when the payload gets returned.

I'm happy to do a PR if there's no reason for not supporting it

**Comment by rkaw92** [comment]
As a user, I would be opposed to having such a functionality in the library itself, so that it can stay more focused. What if a claim is an array, or a complex object, that needs application-level verification? Surely the library can't (and shouldn't) cover such cases. Instead, I would expect the developer to encapsulate this library in something that understands claims.

**Comment by ziluvatar** [comment]
We have been touching a bit at different moments:
* https://github.com/auth0/node-jsonwebtoken/pull/563#issuecomment-459443236
* https://github.com/auth0/node-jsonwebtoken/issues/271
I will close this issue as duplicated and keep ^ 271

If we develop this support it should be in a more generic way where the consumer could define the validation. (@rkaw92 is right too).
