### ISSUE TITLE
HS256 - JWT invalid signature

### ISSUE THREAD

**Issue by antoine-coulon** [auth0/node-jsonwebtoken#584]
Hi, 

I'm having trouble with Jwt and especially an error "Invalid Signature".

I'm generating a token after the user logs in.
```

userSchema.methods.generateJwt = function() {
  var expiry = new Date();
  expiry.setDate(expiry.getDate() + 2);
  return jwt.sign({
    _id: this._id,
    username: this.username,
    name: this.lastname,
    exp: parseInt(expiry.getTime() / 1000),
  }, process.env.SRCT,  {
    algorithm: 'HS256'
  });
}
```
Then I'm creating an express-jwt middleware to add it to routes :

```
var auth = jwt({
  secret: process.env.SRCT,
  userProperty: 'payload'
});
```
Used like this :

`router.get('/', auth, ctrlUser.slash);`

My JWT created is passed in the front end request (Authorization bearer) and is the same as the one created right after the login, according to the debugger.

But unfortunatly, I'm still having the error {"message":"UnauthorizedError: invalid signature"} after each request to the nodejs backend.

By the way, I also went to jwt.io and I tested the Token, it appears to be "Valid signature". Why would the server tell me it is invalid if so?

Thanks in advance

**Comment by safarmer** [comment]
From what I could see from investigating the same issue, the key if passed as a base64 string is being used as raw bytes and is not being converted from base64 to binary.

I had been running into this issue in a round about kind of way. I am integrating with a service that uses this library to generate tokens. When I was testing my implementation based on their spec, I was getting invalid responses even though jwt.io was telling me the token was correct. 

I was able to dump the tokens the other library was generating and they were not valid. When I unchecked the box for base 64 encoded keys the token was able to validate. I was also able to replicate this in my Java implementation by using the raw bytes of the base64 key as the JWT key rather than decoding.

To get my test cases to pass, I essentially I went from using base64Decode(key) to key.toByteArray() for the input to the JWT library I am using.

**Comment by ziluvatar** [comment]
@antoine-coulon could you put some `console.log`'s here and there to show: the token, the secret (not the real one, a fake one that makes it fail) in both places when it signs and when `jwt()` is configured, and also the stack for the error (you can remove the lines about your own code) ?
