### ISSUE TITLE
403 forbidden error

### ISSUE THREAD

**Issue by johankayati** [auth0/node-jsonwebtoken#621]
We are getting 403 forbidden error when we try to install this package. all other packages works fine. please help

error 403 forbidden: jsonwebtoken@latest

**Comment by johankayati** [comment]
it used to work untill last week. started failing from yesterday.

**Comment by panva** [comment]
@johankayati we're not responsible for the runtime or availability of [npmjs.com](https://npmjs.com) package registry and we did not release any new version in the past ~4 months.

[status.npmjs.org](https://status.npmjs.org) looks okay and I can get a fresh installation through so you may be looking at a network or otherwise isolated local issue.

I'm going to close this as there's no TODO to be done from our side.
