### ISSUE TITLE
jwt.verify(token,secret) take too long, for one to three minutes

### ISSUE THREAD

**Issue by kekobin** [auth0/node-jsonwebtoken#631]
Hi,there:
I use jwt.verify(token,secret) to decode token, but it is not stable.sometimes it takes just 100ms, but sometimes one more minutes.how is that ?

**Comment by ziluvatar** [comment]
First time I see that. Is still happening to you? Isn't another part of the system preventing the node process to execute it properly?

We don't have any benchmark about the library though.

**Comment by jaywcjlove** [comment]
@zamd 

```bash
ER_DATA_TOO_LONG: Data too long for column 'session_id' at row 1
```

Generated token is too long

```js
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiNSIsImlhdCI6MTU3ODQ2Mzk3NSwiZXhwIjoxNTc4NDY0MDM1fQ.WxBGSsldENF2JpELVExs4ILIxprQFi1GV1PxUN30GuE'.length
// => 143
```

https://github.com/chill117/express-mysql-session/blob/c619e09e9395a42288e850b9e589103672cce789/schema.sql#L2

Due to the preset design limitation of the [express-mysql-session](https://github.com/chill117/express-mysql-session/blob/c619e09e9395a42288e850b9e589103672cce789/schema.sql#L2) table.

**Comment by ziluvatar** [comment]
@jaywcjlove I don't think your last message has relation with the initial topic.
Closing.
