### ISSUE TITLE
Add option to ignore signature validation (e. g. for dev/test purposes)

### ISSUE THREAD

**Issue by rockebee** [auth0/node-jsonwebtoken#665]
### Describe the problem you'd like to have solved

> In dev and test environments it may be feasible to work with a test JWT token which has no valid signature, e. g. for cases where the token provider can not be modified to create tokens in a manner how a relying party needs it for a special edge situation. In this case the JWT payload could be modified manually be the developer to match/test the requirement, but the current jsonwebtoken implementation does not allow to use this invalid token within ```jwt.verify()``` function.

### Describe the ideal solution

> Adding a new option ```ignoreSignature``` to the existing set of options (like ```ignoreExpiration``` and ```ignoreNotBefore```) would allow developers to use self-modified tokens for tests but still having checks for proper ```issuer```, ```subject```, ```audience``` in place.

## Alternatives and current work-arounds

> Using of ```jwt.decode()``` instead of ```jwt.verify()``` helps in at least getting the JWT decoded properly, but as mentioned above does not allow for getting other verification checks run (```issuer``` etc.)

### Additional context

> no additional input here

**Comment by rockebee** [comment]
One more note: From looking into source code it should be easy to get implemented by modifying ```verify.js``` somewhere around here: https://github.com/auth0/node-jsonwebtoken/blob/a6235fa561b5c30884c97ea0b30c3db3b546ae2c/verify.js#L126-L134

**Comment by ziluvatar** [comment]
I think it is too risky to add that option to the `verify()` function, without signature the rest of checks do not make sense, you can not trust the information you got. Also I think they key point is here:
> for a special edge situation

I'd say to try to solve that special edge case by fixing the interoperability between both.

Other possible workarounds:
* You could mock the Token Provider depending on your tests.
* You can build an abstraction using `.decode()` as you said in testing, really... any other check without signature verification can be forced to fail whenever you want.
  * Even that abstraction could do `decode()` + `sign()` another token with same payload and `none` algorithm or use one secret for testing an use one of `HS` algorithms + `verify()`.

Anyway whatever you do it has the risk to end up running in production due to a misconfiguration. 😅 

PS: Nice way to present your request 👏
