### ISSUE TITLE
TypeError: e is not an object or null

### ISSUE THREAD

**Issue by artoryas** [auth0/node-jsonwebtoken#701]
### Description

 I was embedding metabase dashboard in my angular app thus I needed to use jsonwebtoken. I have used jwt.sign method to encrypt my data in token. By starting project on localhost with 'ng serve' everything works fine, but if I will build project I keep getting an error in console **TypeError: e is not an object or null**
### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
> - Code sample to reproduce the issue

    let METABASE_SITE_URL = 'MYURL';
    let METABASE_SECRET_KEY = 'SECRETKEY';
    let payload = {
      resource: {dashboard: 416},
      params: {},
      exp: Math.round(Date.now() / 1000) + (10 * 60)
    };
    
    let token = jwt.sign(payload, METABASE_SECRET_KEY, { 
      algorithm: 'HS256'
    });
> - Log files (redact/remove sensitive information)

ERROR Error: "Uncaught (in promise): TypeError: e is not an object or null
> - Application settings (redact/remove sensitive information)
> - Screenshots

### Environment

> Please provide the following:

- **Version of this library used:** 8.3.7
- **Version of the platform or framework used, if applicable:**  Angular 6.1.6, Node 12.14.0
- **Other relevant versions (language, server software, OS, browser):** Windows
- **Other modules/plugins/libraries that might be involved:**

**Comment by panva** [comment]
That's because `jsonwebtoken` is not built to be transpiled, under its hood it uses node's `crypto` module that your webpack bundle has a registered polyfill for. We can't control that, **nor do we actually support browser environment as a runtime for this module**.

We are not providing `jsonwebtoken` for the browser platform and would recommend use of JWT modules that utilize the browser built-in [`Web Cryptography API`](https://www.w3.org/TR/WebCryptoAPI/) instead.
