### ISSUE TITLE
If a token is both invalid AND expired - which exception will be thrown? [security flaw]

### ISSUE THREAD

**Issue by alex-jitbit** [auth0/node-jsonwebtoken#702]
I need to know for sure. Otherwise this uncertainity opens a vector for an attack.

I can provide an example attack scenario if you really need it.

UPDATE: just ran a debug session. Yes, it throws me "expired" even if the signature is not valid.

This is a flaw since a developer might assume "if JsonWebTokenError hasn't been thrown - mean the signature is valid".

PS. Also this component forces me to base my logic on errors and exceptions which is bad practice. But that's another question.

**Comment by cdhowie** [comment]
This is not a security flaw.

An invalid token is an invalid token. It does not matter for what reason an exception is thrown -- if `verify()` throws then __you should not trust anything in the token, period.__  I would assume that the expiration is checked first because it is substantially cheaper to compare two integers than to validate a signature, so the failure is faster.

To be frank, the security flaw is in your own code where you read data from the token even though it is expired.  If you are doing that then you are knowingly taking data from an invalid token.

If you really want to know if the signature is valid regardless of the declared expiration time of the token, that's what `verify()`'s `ignoreExpiration` option is for.

**Comment by alex-jitbit** [comment]
@cdhowie thanks for pointing me at `ignoreExpiration`

**Comment by cdhowie** [comment]
> Also, if a token is expired - it usually triggers some renewal workflow

Usually this would happen in the frontend, however, and you still would not trust anything in the token. You'd usually kick someone back to the login screen, for example. In this case, expiration detection can happen entirely in the frontend without relying on the backend server's response. (Is `exp < (Date.now() / 1000)`?)

If you're talking about renewing an almost-expired token, in that case you _still_ usually don't want to accept expired tokens or trust them. Instead, if a token is within N minutes/hours/days from expiring, you could trigger your renewal workflow. In that case you still have a valid token, but you can inspect the `exp` value to determine if you need to preemptively renew it.
