### ISSUE TITLE
jsonwebtoken doesn't supported in webpack 5

### ISSUE THREAD

**Issue by Sahar3dsig** [auth0/node-jsonwebtoken#765]
when building react with webpack5, I receive the error:

<img width="775" alt="Screen Shot 2021-02-16 at 17 26 00" src="https://user-images.githubusercontent.com/56968178/108084128-85530c00-707c-11eb-9907-7ee660136165.png">

**Comment by panva** [comment]
That's because `jsonwebtoken` is not built to be transpiled for the web browser runtime, under its hood it uses node's `crypto` module. We actually support browser environment as a runtime for this module.

We are not providing `jsonwebtoken` for the browser platform and would recommend use of JWT modules that utilize the browser built-in [`Web Cryptography API`](https://www.w3.org/TR/WebCryptoAPI/) instead, e.g. [`jose`](https://github.com/panva/jose).

**Comment by darioackermann** [comment]
@Sahar3dsig 

You can for example add this to your webpack config:

```
    resolve: {
      fallback: {
        "buffer": require.resolve('buffer/'),
      }
    },
    plugins: [
      new webpack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
      }),
    ]
  
```
